services:
  better-discord-webhooks:
    # image: ghcr.io/thelovinator1/better-discord-webhooks:master
    build: .
    env_file:
      - .env
    container_name: better-discord-webhooks
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
    ports:
      - "20526:5000"
    restart: unless-stopped
